### ISSUE TITLE
Kodi crash on every run of Artwork Dump

### ISSUE THREAD

**Issue by belzebud** [rmrector/script.artwork.dump#2]
I experience a crash every time I run Artwork Dump in Kodi Matrix.

At about 5% completion I receive a notification saying the Artwork Dump service is unavailable. It then zips through to around 98%, where it sits for a minute. I see it naming movies, but it then crashes before it gets through movies starting with "B".

 Arch: x86_64
 Kernel: Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021
 Release: Linux Mint 20.1 (Ulyssa)

My crashlog has been uploaded:
http://s000.tinyupload.com/index.php?file_id=84520274044935014129

**Comment by rmrector** [comment]
What exactly is the problem?

There are no crashes here, just a couple of warnings that the fanart.tv web service was temporarily unavailable - it looks like it only affected a few images. That happens, it is a web service provided for free. It will probably work if you run it again.

**Comment by belzebud** [comment]
I'm not sure why there's no crash in the Kodi crash log. Kodi definitely crashes to desktop every time artwork dump is ran on my system. I had it running with library updates upon Kodi starting up, but I disabled that due to the amount of crashes. It also happens when I run artwork dump manually from the add-on menu.

I used artwork beef for years and I never had a crash when running it.

When I get back home in a few days I will try again, but this was occurring every time artwork dump ran over the course of a week, ever since I installed it.

If you want any additional logging enabled I can do so and upload the new crash log if it does crash again.

**Comment by rmrector** [comment]
ahh, Kodi crashed. That seems to be happening with non-Unicode strings, but I can't tell why in this case. Does it always crash at the same place in the library, "Black Panther Collection" or the movie set after that?

**Comment by rmrector** [comment]
Is 0.2.0 behaving any better for you?

If not I'll need a new debug log.

**Comment by belzebud** [comment]
Sorry, things have been very hectic.
Yes, from what I remember it always crashed there. I thought that was odd so I tried to play close attention. The messages sometimes move too fast to read, so I may have missed something.

I upgraded to 0.2.0 just now and it didn't crash when running. It seems like whatever was doing it has been fixed.

Thanks for the help.
