### ISSUE TITLE
Cannot install repository from link provided 

### ISSUE THREAD

**Issue by samg80** [rmrector/script.artwork.dump#8]
@rmrector 
My Kodi background pics are very dull and I was looking to get some new and interesting wallpapers/pics for my Kodi 19.1 Matrix on FireTV. I followed the first step you provided in the Read me file:
-" ## Installation
Install my [dev repository][1] to get updates delivered to you automatically. After the repo is
installed, Artwork Dump can be installed from "Program add-ons". Artwork Dump can also be installed
with a [single zip file][2], but you will have to update manually.
[1]: https://github.com/rmrector/repository.rector.stuff/raw/python3/latest/repository.rector.stuff-latest.zip"
However, after adding the source and going to install the repository, I see **repository.rector.stuff** but when I click it, it is showing nothing!
Is that repository still active? I wonder if I might be doing something wrong - I made sure that I typed the URL correctly and no typos 
Please advise.

**Comment by rmrector** [comment]
Download the zip file and install in Kodi, it is not a "source" to be added.
